// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package com.hu.grpc.compileFile;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hu.grpc.compileFile.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回结果
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 返回结果
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
