// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package com.hu.grpc.compileFile;

public final class HelloWorld {
  private HelloWorld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hu_grpc_compileFile_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hu_grpc_compileFile_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hu_grpc_compileFile_Greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hu_grpc_compileFile_Greeting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hu_grpc_compileFile_PinnedPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hu_grpc_compileFile_PinnedPart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020helloWorld.proto\022\027com.hu.grpc.compileF" +
      "ile\"/\n\006Person\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlas" +
      "t_name\030\002 \001(\t\"\033\n\010Greeting\022\017\n\007message\030\001 \001(" +
      "\t\"e\n\nPinnedPart\022\020\n\010partType\030\001 \001(\005\022\021\n\tign" +
      "oreMcc\030\002 \001(\010\0222\n\007dataSet\030\003 \003(\0132!.com.hu.g" +
      "rpc.compileFile.Greeting2\272\001\n\021HelloWorldS" +
      "ervice\022P\n\010sayHello\022\037.com.hu.grpc.compile" +
      "File.Person\032#.com.hu.grpc.compileFile.Pi" +
      "nnedPart\022S\n\013sayGreeting\022\037.com.hu.grpc.co" +
      "mpileFile.Person\032!.com.hu.grpc.compileFi" +
      "le.Greeting0\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hu_grpc_compileFile_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hu_grpc_compileFile_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hu_grpc_compileFile_Person_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_hu_grpc_compileFile_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hu_grpc_compileFile_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hu_grpc_compileFile_Greeting_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_hu_grpc_compileFile_PinnedPart_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hu_grpc_compileFile_PinnedPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hu_grpc_compileFile_PinnedPart_descriptor,
        new java.lang.String[] { "PartType", "IgnoreMcc", "DataSet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
