// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package com.hu.grpc.compileFile;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hu.grpc.compileFile.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * first_name 作为第一个参数
   * </pre>
   *
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <pre>
   * first_name 作为第一个参数
   * </pre>
   *
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <pre>
   * last_name 作为第二个参数
   * </pre>
   *
   * <code>string last_name = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <pre>
   * last_name 作为第二个参数
   * </pre>
   *
   * <code>string last_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
