// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package com.hu.grpc.compileFile;

public interface PinnedPartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hu.grpc.compileFile.PinnedPart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 partType = 1;</code>
   */
  int getPartType();

  /**
   * <code>bool ignoreMcc = 2;</code>
   */
  boolean getIgnoreMcc();

  /**
   * <code>repeated .com.hu.grpc.compileFile.Greeting dataSet = 3;</code>
   */
  java.util.List<com.hu.grpc.compileFile.Greeting> 
      getDataSetList();
  /**
   * <code>repeated .com.hu.grpc.compileFile.Greeting dataSet = 3;</code>
   */
  com.hu.grpc.compileFile.Greeting getDataSet(int index);
  /**
   * <code>repeated .com.hu.grpc.compileFile.Greeting dataSet = 3;</code>
   */
  int getDataSetCount();
  /**
   * <code>repeated .com.hu.grpc.compileFile.Greeting dataSet = 3;</code>
   */
  java.util.List<? extends com.hu.grpc.compileFile.GreetingOrBuilder> 
      getDataSetOrBuilderList();
  /**
   * <code>repeated .com.hu.grpc.compileFile.Greeting dataSet = 3;</code>
   */
  com.hu.grpc.compileFile.GreetingOrBuilder getDataSetOrBuilder(
      int index);
}
